# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Carthage"
  before_all do
    carthage(
      command: "bootstrap",
      platform: "iOS",
      cache_builds: true,  
    )
  end
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "DEV",
      code_coverage: true
    )
  end

  desc "Runs coverage"
  lane :coverage do
    test
    slather(
      travis: true,
      scheme: "DEV",
      #coveralls: true,
      proj: "DEV.xcodeproj,"
      #workspace: "DEV.xcworkspace"
    )
  end
end
