name: CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test Suite
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: XCode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.2'
      - name: Build and test
        run: |
          fastlane test

